version: '2'

services:
  app:
    build:
      image: brain/mapper
      dockerfile: Dockerfile

  aws_dockercfg:
    image: codeship/aws-ecr-dockercfg-generator
    add_docker: true
    encrypted_env_file: aws.env.encrypted
